# Generated by Django 5.2.2 on 2025-06-15 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_ent', models.CharField(max_length=2)),
                ('nomgeo', models.CharField(max_length=50)),
                ('nom_abrev', models.CharField(max_length=10)),
                ('pob_total', models.IntegerField()),
                ('pob_femenina', models.IntegerField()),
                ('pob_masculina', models.IntegerField()),
                ('total_viviendas_habitadas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_loc', models.CharField(max_length=4)),
                ('nomgeo', models.CharField(max_length=100)),
                ('ambito', models.CharField(max_length=10)),
                ('longitud', models.FloatField()),
                ('latitud', models.FloatField()),
                ('altitud', models.IntegerField()),
                ('pob_total', models.IntegerField()),
                ('total_viviendas_habitadas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Asentamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_asen', models.CharField(max_length=4)),
                ('nom_asen', models.CharField(max_length=255)),
                ('tipo_asen', models.CharField(max_length=30)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inegi_app.localidad')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_mun', models.CharField(max_length=3)),
                ('nomgeo', models.CharField(max_length=80)),
                ('pob_total', models.IntegerField()),
                ('pob_femenina', models.IntegerField()),
                ('pob_masculina', models.IntegerField()),
                ('total_viviendas_habitadas', models.IntegerField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inegi_app.estado')),
            ],
        ),
        migrations.AddField(
            model_name='localidad',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inegi_app.municipio'),
        ),
    ]
